server:
  port: 8888
spring:
  application:
    name: config-server 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MiguelProgrammer/config-server
          # pode usar username e password em caso de repositórios privados 
          default-label: main
          search-paths:
          - 'greeting-service*'
          
          
          