name: Continuous Integration With Github
on:
  push:
    branches:
      - microservices
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 
      - name: Login in to Docker Hub  
        uses: docker/login-action@v1
        with:
          name: my-app-microservices/microservices
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          default_branch: microservices
